import { Game } from './types';

export const TRENDING_GAME_IDS: string[] = [
    'forzahorizon',
    'gta5',
    'rooftops',
    'beamng',
    'assettocorsa',
    'cookingdom',
    'farmmanager',
];

export const GAMES: Game[] = [
  {
    id: 'efootball',
    name: 'eFootball™ 2024',
    shortName: 'eFootball™ 2024',
    icon: 'https://i.pinimg.com/736x/9b/92/fd/9b92fd839c1c4403882a75934816ccd7.jpg',
    rating: 4.9,
    downloads: '890K',
    description: 'Experience the new era of digital football! Play with the biggest teams and build your dream squad in this realistic soccer simulation.',
    author: 'EgoMod',
  },
  {
    id: 'forzahorizon',
    name: 'Forza Horizon 5 Mobile',
    shortName: 'Forza Horizon 5 Mobile',
    icon: 'https://images.seeklogo.com/logo-png/40/1/forza-horizon-5-logo-png_seeklogo-406612.png',
    rating: 4.8,
    downloads: '1.2M',
    description: 'Explore the vibrant open world of Mexico with limitless driving action in hundreds of the world’s greatest cars.',
    author: 'EgoMod',
  },
  {
    id: 'gta5',
    name: 'GTA 5 Mobile Premium',
    shortName: 'GTA 5 Mobile',
    icon: 'https://i.pinimg.com/736x/8f/01/03/8f010359c57da7850e723fa17a53b55e.jpg',
    rating: 4.6,
    downloads: '340K',
    description: 'Step into the lives of three criminals as they risk everything in a series of daring heists in the sprawling city of Los Santos.',
    author: 'EgoMod',
  },
  {
    id: 'assettocorsa',
    name: 'Assetto Corsa Mobile',
    shortName: 'Assetto Corsa Mobile',
    icon: 'https://image.api.playstation.com/cdn/EP4040/CUSA01797_00/NMcAucyANMnYMNkz6V5vk9f5YXty2mCz.png',
    rating: 4.7,
    downloads: '850K',
    description: 'The ultimate racing simulator that offers a realistic driving experience with a wide variety of cars and detailed tracks.',
    author: 'EgoMod',
  },
  {
    id: 'beamng',
    name: 'BeamNG.drive Mobile',
    shortName: 'BeamNG.drive Mobile',
    icon: 'https://avatars.githubusercontent.com/u/6404024?s=280&v=4',
    rating: 4.6,
    downloads: '953K',
    description: 'A realistic and immersive driving game offering near-limitless possibilities with its soft-body physics engine.',
    author: 'EgoMod',
  },
  {
    id: 'fc24',
    name: 'FC Mobile 24 Premium',
    shortName: 'FC Mobile 24',
    icon: 'https://yt3.googleusercontent.com/VJpwQREmZAtECuQC-yveNLKyc_xzI9bKhtON0RdF9lJaer-W-dZr3d_1QzchUUZVXAeGe1D6ErU=s900-c-k-c0x00ffffff-no-rj',
    rating: 4.9,
    downloads: '1.4M',
    description: "Build your Ultimate Team with legendary football stars and compete in thrilling matches. The world's game, now in your pocket.",
    author: 'EgoMod',
  },
  {
    id: 'rooftops',
    name: 'Rooftops & Alleys Mobile',
    shortName: 'Rooftops & Alleys',
    icon: 'https://i.postimg.cc/W1bm7TRt/Fh-T2ixl-Wyl9TPswg-KLF0j-Pp9j-Nuq.png',
    rating: 4.4,
    downloads: '49K',
    description: 'Experience the thrill of parkour and freerunning in this fast-paced game. Flow through urban environments with style and precision.',
    author: 'EgoMod',
  },
  {
    id: 'cookingdom',
    name: 'Watch Dogs 2 Mobile',
    shortName: 'Watch Dogs 2 Mobile',
    icon: 'https://i.postimg.cc/Xvg3XNm6/Watch-Dogs-2-Logo.png',
    rating: 4.7,
    downloads: '1.1M',
    description: 'Play as a brilliant young hacker and explore the massive and dynamic open-world of the San Francisco Bay Area.',
    author: 'EgoMod',
  },
  {
    id: 'farmmanager',
    name: 'Euro Truck Simulator 2',
    shortName: 'Euro Truck Simulator 2',
    icon: 'https://i.pinimg.com/564x/32/ae/e5/32aee5919f1c4e81da58627d21b3323a.jpg',
    rating: 4.5,
    downloads: '533K',
    description: 'Travel across Europe as king of the road, a trucker who delivers important cargo across impressive distances.',
    author: 'EgoMod',
  },
  {
    id: 'racinglegends',
    name: 'Racing Legends Offline',
    shortName: 'Racing Legends Offline',
    icon: 'https://cdn.aptoide.com/imgs/5/5/3/5530baa471f8b7ac41cc894144d6c5a1_icon.png',
    rating: 4.8,
    downloads: '461K',
    description: 'Get behind the wheel of legendary classic cars and compete in thrilling offline races. Master the art of driving!',
    author: 'EgoMod',
  },
];